### ISSUE TITLE
compile failed!

### ISSUE THREAD

**Issue by AnShuai666** [BluewhaleRobot/GalileoSDK#16]
`xiaoqiang@xiaoqiang-desktop:~/Documents/GalileoSDK/GalileoSDK/build$ make -j
Scanning dependencies of target GalileoSDK
[ 20%] Building CXX object CMakeFiles/GalileoSDK.dir/HttpConnection.cpp.o
[ 40%] Building CXX object CMakeFiles/GalileoSDK.dir/GalileoSDK.cpp.o
[ 60%] Building CXX object CMakeFiles/GalileoSDK.dir/iot.cpp.o
[ 80%] Building CXX object CMakeFiles/GalileoSDK.dir/mutils.cpp.o
/home/xiaoqiang/Documents/GalileoSDK/GalileoSDK/HttpConnection.cpp: In member function ‘std::__cxx11::string GalileoSDK::HttpConnection::socketHttp(std::__cxx11::string, std::__cxx11::string, int)’:
/home/xiaoqiang/Documents/GalileoSDK/GalileoSDK/HttpConnection.cpp:34:55: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         write(sockfd, request.c_str(), request.size());
                                                       ^
/home/xiaoqiang/Documents/GalileoSDK/GalileoSDK/GalileoSDK.cpp: In member function ‘GalileoSDK::GALILEO_RETURN_CODE GalileoSDK::GalileoSDK::Connect(GalileoSDK::ServerInfo)’:
/home/xiaoqiang/Documents/GalileoSDK/GalileoSDK/GalileoSDK.cpp:301:2: error: ‘setHostRecord’ is not a member of ‘ros::network’
  ros::network::setHostRecord("xiaoqiang-desktop", server.getIP());
  ^
CMakeFiles/GalileoSDK.dir/build.make:62: recipe for target 'CMakeFiles/GalileoSDK.dir/GalileoSDK.cpp.o' failed
make[2]: *** [CMakeFiles/GalileoSDK.dir/GalileoSDK.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/GalileoSDK.dir/all' failed
make[1]: *** [CMakeFiles/GalileoSDK.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by randoms** [comment]
你应该没有按照文档里面的方法编译。ros的库不能用原版的要用修改版的，里面有些函数是修改版才有的。
